version: '3.1'
services:
  rdm:
    image: docker.pkg.github.com/realdevicemap/realdevicemap/realdevicemap:master
    container_name: atlas-rdm
    networks:
      - atlas-network
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    volumes:
      - ./images:/app/resources/webroot/static/img
      - backups:/app/backups
#     - favicons:/app/resources/webroot/static/favicons
#     - /etc/localtime:/etc/localtime:ro
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      DB_DATABASE: rdmdb
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: rdmuser
      DB_PASSWORD: pokemodrules
      DB_ROOT_USERNAME: root
      DB_ROOT_PASSWORD: pokemodrules
      WEB_SERVER_ADDRESS: 0.0.0.0
      WEB_SERVER_PORT: 9000
      WEBHOOK_SERVER_ADDRESS: 0.0.0.0
      WEBHOOK_SERVER_PORT: 9001
      WEBHOOK_ENDPOINT_TIMEOUT: 30
      WEBHOOK_ENDPOINT_CONNECT_TIMEOUT: 30
      MEMORY_CACHE_CLEAR_INTERVAL: 900
      MEMORY_CACHE_KEEP_TIME: 3600
      RAW_THREAD_LIMIT: 100
      LOG_LEVEL: debug
      NO_BACKUP: 1
      NO_REQUIRE_ACCOUNT: 1
### Uncommenting the following lines will set these values to TRUE (regardless of their value)
#     USE_RW_FOR_QUEST: 1
#     USE_RW_FOR_RAID: 1
#     NO_GENERATE_IMAGES: 1
#     NO_PVP: 1
#     NO_IV_WEATHER_CLEARING: 1
#     NO_CELL_POKEMON: 1
#     NO_MEMORY_CACHE: 1
### Uncommenting The following lines will start RDM in lldb and store crash reports in the backups folder
### Running in lldb will use a bit more resources. (Running RDM works like usual)
#   entrypoint: ["/bin/sh", "-c", "lldb -b -o \"file ./RealDeviceMap\" -o \"breakpoint set --file main.swift --line 17\" -o \"run\" -o \"process handle SIGPIPE -n true -p true -s false\" -o \"continue\" -k \"bugreport unwind --outfile ./backups/crash-$$(date +%s).log\" -k \"exit\""]
#   cap_add:
#     - SYS_ADMIN
#   security_opt:
#     - seccomp=unconfined
#     - apparmor=unconfined
  db:
    image: mariadb:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --binlog-expire-logs-seconds=86400
    container_name: atlas-db
    networks:
      - atlas-network
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pokemodrules
      MYSQL_DATABASE: rdmdb
      MYSQL_USER: rdmuser
      MYSQL_PASSWORD: pokemodrules
    volumes:
      - ./data:/var/lib/mysql
#     - /etc/localtime:/etc/localtime:ro
  pma:
    image: phpmyadmin:latest
    container_name: atlas-pma
    networks:
      - atlas-network
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 9200:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: pokemodrules
      UPLOAD_LIMIT: 300M
  tools:
    container_name: atlas-rdmtools
    networks:
      - atlas-network
    build: ./tools
    depends_on:
      - rdm
    volumes:
      - ./tools/config/config.php:/var/www/html/config/config.php
      - ./tools/config/docker-php-maxexectime.ini:/usr/local/etc/php/conf.d/docker-php-maxexectime.ini
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - 9100:80
  reactmap:
    image: ghcr.io/watwowmap/reactmap:main
    container_name: atlas-reactmap
    command: sh -c "yarn start"
    restart: unless-stopped
    networks:
      - atlas-network
    depends_on:
      - rdm
    volumes:
      #- ./server/src/configs/areas.json:/home/node/server/src/configs/areas.json
      - ./reactmap-local.json:/home/node/server/src/configs/local.json
      #- ./server/src/configs/geofence.json/:/home/node/server/src/configs/geofence.json
      - ./reactmap-env:/home/node/.env
    ports:
      - "9300:8080"
volumes:
  backups:
    driver: local
networks:
  atlas-network:
#   images:
#     driver: local
#   data:
#     driver: local
# favicons
#   driver: local
